<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/custom_theme.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Space+Grotesk:600|PT+Sans:200,300,400');
$this->headScript()->prependFile($this->assetUrl('js/custom.js'));
$this->headScript()->prependFile($this->assetUrl('js/thedaily.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$userBar = $this->userBar();
$this->trigger('view.layout');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            #top-nav > ul > li > a,
            #featured .record a,
            .site-page-pagination a,
            #top-nav > ul > li > a,
            #featured .record a,
            .site-page-pagination a,
            .results .result-title a {
                color: <?php echo $accentColor; ?>
            }
            
            p a,
            span a,
            .button,
            button,
            input[type="submit"],
            .secondary-nav li a,
            .pagination a.button,
            .item-pagination a,
            #featured .featured-meta h3,
            .advanced-search,
            .value a span,
            .sub-menu,
            .results li a,
            .results > ul + a {
                background-color: <?php echo $accentColor; ?>;
            }
            <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <header>
            <h1>
                <a href="<?php echo $site->url(); ?>" class="site-title">
                <?php if ($this->themeSetting('logo')): ?>
                    <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                <?php else: ?>
                    <?php echo $escape($siteTitle); ?>
                <?php endif; ?>
                </a>
            </h1>
            <div id="open-menu">
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
            </div>
            <div id="search-container">
                <?php echo $this->partial('common/search-form'); ?>
                <button type="button" class="search-toggle" aria-label="Toggle search"></button>
            </div>
            <nav id="top-nav" class="closed">
            <button type="button" class="menu-toggle" aria-label="Toggle Menu"></button>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>
        </header>
        <?php $content = $this->content;
            $dom = new DomDocument();
            libxml_use_internal_errors(true);
            $dom->loadHtml($content);
            libxml_clear_errors();
            $xpath = new DOMXPath($dom);
        ?>
        <?php $path = $_SERVER["REQUEST_URI"];
        if ($path == "/s/1972_mostra/page/home"): #the homepage has another layout but I don't like this solution ?>
            <div id="content_home" role="main">
                <section class="home_image_section">
                    <div class="overlay">
                        <div id="exhibit_intro">
                            <div class="intro_text">
                            <?php $result = $xpath->query("//div[@class='text_1']");
                                $node = $result->item(0);
                                echo $dom->saveHTML($node);
                            ?>
                            </div>
                            <a class="arrow-down" href="#intro"><img src="/themes/1972_thedaily/asset/img/chevron-down-solid.png"></a>
                        </div>
                    </div>
                </section>
                <section class="home_section" id="intro">
                    <div class="title_home_text">
                        <h2>La mostra</h2>
                    </div>
                    <div class="home_text">
                        <?php $result = $xpath->query("//div[@class='text_2']");
                            $node = $result->item(0);
                            echo $dom->saveHTML($node);
                        ?>
                        <a class='arrow-down' href="#logo"><img src="/themes/1972_thedaily/asset/img/chevron-down-solid.png"></a>
                    </div>
                </section>
                <section class="home_section home_section--logo" id="logo">
                    <div class="wrap">
                        <div class="home_text">
                        <?php $result = $xpath->query("//div[@class='text_3']");
                            $node = $result->item(0);
                            echo $dom->saveHTML($node);
                        ?>
                        </div>
                        <div class="composition">
                            <a href="design"><img src="/themes/1972_thedaily/asset/img/logo_minaBN2.png" class="composition__logo composition__logo--mina"></a>
                            <a href="moda"><img src="/themes/1972_thedaily/asset/img/logo_figuraBN2.png" class="composition__logo composition__logo--figura"></a>
                            <a href="storia"><img src="/themes/1972_thedaily/asset/img/logo_macchinaBN2.png" class="composition__logo composition__logo--macchina"></a>
                            <img src="/themes/1972_thedaily/asset/img/versace_firma.jpeg" class="versace_firma">
                        </div>
                    </div>
                </section>
            </div>
        <?php elseif ($path == "/s/1972_mostra/page/design"): #omeka-s #the design page has another layout but I don't like this solution ?> 
            <div id="content" role="main">
                <img src="/themes/1972_thedaily/asset/img/logo_minaLITTLE.png" class="title_image"/><div class="rectangle_title"><h2>Design — MoMA 1972</h2></div>
                    <section class="wrap percorsi_page">
                        <div class="percorsi_text">
                        <iframe width= "100%" height="600" src="https://storiiies.cogapp.com/viewer/662du/MoMA-1972?embed=true" title="Percorso Design — MoMA 1972"></iframe>
                            <form action="https://storiiies.cogapp.com/viewer/662du/MoMA-1972" target="_blank">
                                <button type="submit" style="float:right; margin-right: 10%; margin:10px; margin-bottom: 20px" value="Vai al percorso">Ingrandisci</button>
                            </form>
                        </div>
                    </section>
                    <section>
                        <div class="see_more">
                        <?php echo $this->content; ?> 
                        </div>
                    </section>
            </div>
        <?php elseif ($path == "/s/1972_mostra/page/moda"): #omeka-s #the moda page has another layout but I don't like this solution ?> 
            <div id="content" role="main">
                <img src="/themes/1972_thedaily/asset/img/logo_figuraLITTLE.png" class="title_image"/><div class="rectangle_title"><h2>Moda — Milano 1971/1972</h2></div>
                <section class="wrap percorsi_page">
                    <div class="percorsi_text">
                        <iframe width= "100%" height="600" src="https://exhibit.so/exhibits/kAaUsjel7VohRCIgqS6a?embedded=true" title="Percorso Moda — Milano 1971/1972"></iframe>
                        <form action="https://exhibit.so/exhibits/kAaUsjel7VohRCIgqS6a" target="_blank">
                            <button type="submit" style="float:right; margin-right: 10%; margin:5%" value="Vai al percorso">Ingrandisci</button>
                        </form>
                    </div>
                </section>
                <section>
                <div class="see_more">
                    <?php echo $this->content; ?>    
                </div>
                </section>
            </div>
        <?php elseif ($path == "/s/1972_mostra/page/storia"): #omeka-s #the moda page has another layout but I don't like this solution ?> 
            <div id="content" role="main">
                <img src="/themes/1972_thedaily/asset/img/logo_macchinaLITTLE.png" style="margin-top:30px;" class="title_image"/><div class="rectangle_title"><h2>Storia</h2></div>
                <?php echo $this->content; ?>    
            </div>
        <?php elseif ($path == "/s/1972_mostra/page/designer"): #omeka-s #the designer page has another layout but I don't like this solution ?> 
            <div id="content" role="main"> 
                <div class="rectangle_title"><h2>Designer</h2></div>
                <div class="row-grid">
                    <div class="column-grid">
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/2d691a05c259391b312e7ce6d27f956791212426.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Albini</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/ca75609694b5af8d26bb0c1675cca44b90ad0042.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Archizoom associati</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/2d691a05c259391b312e7ce6d27f956791212426.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Armani</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/107ec034fffd7c1678fa26e46c24696ff8a423a5.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Bellini</div>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="column-grid">
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/bad74ffe4a9d1810522067c0f4372f24e95b155a.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Ferré</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/f405041cea28cbff6f6a6cff56413312d7e322ec.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Krizia</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/d36329f14cc82c6f2eacb66f2ec80c31376e23d2.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Mendini</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/ca75609694b5af8d26bb0c1675cca44b90ad0042.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Moschino</div>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="column-grid">
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/ecef6cd063814a7424e2b18e200a9a45aec17b09.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Rosselli</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/7963482719134e8eb67323e09463eb8e43c3d473.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Ruggeri</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/db2fef712b25d337296b605fe4433844924e96d2.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Sotssass</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="armani">
                            <img class="designer__img" src="http://srv-omeka-01.unipr.it/files/original/d3a706079d1a7962a827babfc48cb47ad883c916.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Versace</div>
                            </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php elseif (preg_match("/\/s\/1972_mostra\/page\/designer_.*/", $path)): #the designer page has another layout but I don't like this solution ?> 
            <div id="content_home" role="main">
                <div class="head-mono">                    
                    <span class="mono_link"></span>
                </div>
                <div class="scrolling-wrapper">
                    <span class='arrow-left'><img src="/themes/1972_thedaily/asset/img/chevron-left-solid.png"></span>
                    <span class='arrow-right'><img src="/themes/1972_thedaily/asset/img/chevron-right-solid.png"></span>
                    <?php echo $this->content; ?>
                </div>
            </div>
        <?php else: ?>
            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>
        <?php endif; ?>
        <footer>
            <?php if ($footerContent = $this->themeSetting('footer')): ?>
                <?php echo $footerContent; ?>
            <?php else: ?>
                <?php echo $this->translate('Powered by Omeka S'); ?>
            <?php endif; ?>
        </footer>
    </body>
</html>