<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/custom_theme.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Space+Grotesk:600|PT+Sans:200,300,400');
$this->headScript()->prependFile($this->assetUrl('js/custom.js'));
$this->headScript()->prependFile($this->assetUrl('js/thedaily.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$userBar = $this->userBar();
$this->trigger('view.layout');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            #top-nav > ul > li > a,
            #featured .record a,
            .site-page-pagination a,
            #top-nav > ul > li > a,
            #featured .record a,
            .site-page-pagination a,
            .results .result-title a {
                color: <?php echo $accentColor; ?>
            }
            
            p a,
            span a,
            .button,
            button,
            input[type="submit"],
            .secondary-nav li a,
            .pagination a.button,
            .item-pagination a,
            #featured .featured-meta h3,
            .advanced-search,
            .value a span,
            .sub-menu,
            .results li a,
            .results > ul + a {
                background-color: <?php echo $accentColor; ?>;
            }
            <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <header>
            <h1>
                <a href="<?php echo $site->url(); ?>" class="site-title">
                <?php if ($this->themeSetting('logo')): ?>
                    <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                <?php else: ?>
                    <?php echo $escape($siteTitle); ?>
                <?php endif; ?>
                </a>
            </h1>
            <div id="open-menu">
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
            </div>
            <div id="search-container">
                <?php echo $this->partial('common/search-form'); ?>
                <button type="button" class="search-toggle" aria-label="Toggle search"></button>
            </div>
            <nav id="top-nav" class="closed">
            <button type="button" class="menu-toggle" aria-label="Toggle Menu"></button>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>
        </header>
        <?php $content = $this->content;
            $dom = new DomDocument();
            libxml_use_internal_errors(true);
            $dom->loadHtml($content);
            libxml_clear_errors();
            $xpath = new DOMXPath($dom);
        ?>
        <?php $path = $_SERVER["REQUEST_URI"];
        if ($path == "/s/1972_mostra/page/home"): #the homepage has another layout but I don't like this solution ?>
            <div id="content_home" role="main">
                <section class="home_image_section">
                    <div class="overlay">
                        <div id="exhibit_intro">
                            <div class="intro_text">
                                <h1 class="cover_title">1972. Moda, design, storia</h1>
                                <?php $result = $xpath->query("//div[@class='text_1']");
                                    $node = $result->item(0);
                                    echo $dom->saveHTML($node);
                                ?>
                            </div>
                            <a class="arrow-down" href="#intro"><img src="/themes/1972_thedaily/asset/img/chevron-down-solid.png"></a>
                        </div>
                    </div>
                </section>
                <section class="home_section" id="intro">
                    <div class="title_home_text">
                        <h2>La mostra</h2>
                    </div>
                    <div class="wrap_intro">
                        <img class="versace_image" src="/themes/1972_thedaily/asset/img/versace_logo_ritagliato_bianco.png">
                        <div class="exhibit_descr">
                            <?php $result = $xpath->query("//div[@class='text_2']");
                                $node = $result->item(0);
                                echo $dom->saveHTML($node);
                            ?>
                            <a class='arrow-down' href="#logo"><img src="/themes/1972_thedaily/asset/img/chevron-down-solid.png"></a>
                        </div>
                    </div>
                </section>
                <section class="home_section home_section--logo" id="logo">
                    <div class="wrap">
                        <div class="home_text">
                        <?php $result = $xpath->query("//div[@class='text_3']");
                            $node = $result->item(0);
                            echo $dom->saveHTML($node);
                        ?>
                        </div>
                        <div class="composition">
                            <a href="design"><img src="/themes/1972_thedaily/asset/img/logo_minaBN2.png" class="composition__logo composition__logo--mina"></a>
                            <a href="moda"><img src="/themes/1972_thedaily/asset/img/logo_figuraBN2.png" class="composition__logo composition__logo--figura"></a>
                            <a href="storia"><img src="/themes/1972_thedaily/asset/img/logo_macchinaBN2.png" class="composition__logo composition__logo--macchina"></a>
                            <img src="/themes/1972_thedaily/asset/img/versace_firma.jpeg" class="versace_firma">
                        </div>
                    </div>
                </section>
            </div>
        <?php elseif ($path == "/s/1972_mostra/page/design"): #omeka-s #the design page has another layout but I don't like this solution ?> 
            <div id="content" role="main">
                <img src="/themes/1972_thedaily/asset/img/logo_minaLITTLE.png" class="title_image"/><div class="rectangle_title"><h2>Design — MoMA 1972</h2></div>
                <div class="social-button">
                    <button class="social facebook" data-url="<?php echo $this->serverUrl(true); ?>" title="Share on Facebook">
                        <i class="fa fa-facebook"></i>
                    </button>
                    <button class="social twitter" data-url="<?php echo $this->serverUrl(true); ?>" title="Share on Twitter">
                        <i class="fa fa-twitter"></i>
                    </button>
                </div>
                    <section class="wrap percorsi_page">
                        <div class="percorsi_text">
                        <iframe width= "100%" height="600" src="https://exhibit.so/exhibits/hpUveRDVGB3YOUHatVCi?embedded=true" title="Percorso Design — MoMA 1972"></iframe>
                            <form action="https://exhibit.so/exhibits/hpUveRDVGB3YOUHatVCi" target="_blank">
                                <button type="submit" style="float:right; margin-right: 10%; margin:10px; margin-bottom: 20px" value="Vai al percorso">Ingrandisci</button>
                            </form>
                        </div>
                    </section>
                    <section>
                        <div class="see_more">
                        <?php echo $this->content; ?> 
                        </div>
                    </section>
            </div>
        <?php elseif ($path == "/s/1972_mostra/page/moda"): #omeka-s #the moda page has another layout but I don't like this solution ?> 
            <div id="content" role="main">
                <img src="/themes/1972_thedaily/asset/img/logo_figuraLITTLE.png" class="title_image"/><div class="rectangle_title"><h2>Moda — Milano 1971/1972</h2></div>
                    <div class="social-button">
                    <button class="social facebook" data-url="<?php echo $this->serverUrl(true); ?>" title="Share on Facebook">
                        <i class="fa fa-facebook"></i>
                    </button>
                    <button class="social twitter" data-url="<?php echo $this->serverUrl(true); ?>" title="Share on Twitter">
                        <i class="fa fa-twitter"></i>
                    </button>
                </div>
                <section class="wrap percorsi_page">
                    <div class="percorsi_text">
                        <iframe width= "100%" height="600" src="https://exhibit.so/exhibits/kAaUsjel7VohRCIgqS6a?embedded=true" title="Percorso Moda — Milano 1971/1972"></iframe>
                        <form action="https://exhibit.so/exhibits/kAaUsjel7VohRCIgqS6a" target="_blank">
                            <button type="submit" style="float:right; margin: 2%" value="Vai al percorso">Ingrandisci</button>
                        </form>
                    </div>
                </section>
                <section>
                <div class="see_more">
                    <?php echo $this->content; ?>
                </div>
                </section>
            </div>
        <?php elseif ($path == "/s/1972_mostra/page/storia"): #omeka-s #the moda page has another layout but I don't like this solution ?> 
            <div id="content" role="main">
                <img src="/themes/1972_thedaily/asset/img/logo_macchinaLITTLE.png" style="margin-top:30px;" class="title_image"/><div class="rectangle_title"><h2>Storia</h2></div>
                <div class="social-button">
                    <button class="social facebook" data-url="<?php echo $this->serverUrl(true); ?>" title="Share on Facebook">
                        <i class="fa fa-facebook"></i>
                    </button>
                    <button class="social twitter" data-url="<?php echo $this->serverUrl(true); ?>" title="Share on Twitter">
                        <i class="fa fa-twitter"></i>
                    </button>
                </div>
                <?php echo $this->content; ?>    
            </div>
        <?php elseif ($path == "/s/1972_mostra/page/designer"): #omeka-s #the designer page has another layout but I don't like this solution ?> 
            <div id="content" role="main"> 
                <div class="rectangle_title"><h2>Designer</h2></div>
                <div class="row-grid">
                    <div class="column-grid">
                        <div class="designer_image">
                            <a href="designer_albini">
                            <img class="designer__img" src="https://mostra1972.unipr.it/files/large/eafd800d70e015371384a0fdf16fc46d319debbd.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Albini</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="designer_archizoom">
                            <img class="designer__img" src="https://png.pngtree.com/png-clipart/20190619/original/pngtree-vector-picture-icon-png-image_4013511.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Archizoom associati</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="designer_armani">
                            <img class="designer__img" src="https://mostra1972.unipr.it/files/large/5cff16456be8cb308dbb7552cc8766ea9f4c3b6f.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Armani</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="designer_bellini">
                            <img class="designer__img" src="https://live.staticflickr.com/1893/29196342997_3570bce4ac.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Bellini</div>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="column-grid">
                        <div class="designer_image">
                            <a href="designer_ferre">
                            <img class="designer__img" src="https://png.pngtree.com/png-clipart/20190619/original/pngtree-vector-picture-icon-png-image_4013511.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Ferré</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="designer_krizia">
                            <img class="designer__img" src="https://mostra1972.unipr.it/files/large/2922009b88d3296c22250798aa3e05ca756a8aca.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Krizia</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="designer_mendini">
                            <img class="designer__img" src="https://png.pngtree.com/png-clipart/20190619/original/pngtree-vector-picture-icon-png-image_4013511.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Mendini</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="designer_moschino">
                            <img class="designer__img" src="https://mostra1972.unipr.it/files/large/66170f6f270611e4ca5b1d98a24ed5c5789c1a13.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Moschino</div>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="column-grid">
                        <div class="designer_image">
                            <a href="designer_rosselli">
                            <img class="designer__img" src="https://png.pngtree.com/png-clipart/20190619/original/pngtree-vector-picture-icon-png-image_4013511.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Rosselli</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="designer_ruggeri">
                            <img class="designer__img" src="https://mostra1972.unipr.it/files/large/bfc8f2dc825811b2214f58a44b0dcb90e1167fb2.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Ruggeri</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="designer_sottsass">
                            <img class="designer__img" src="https://png.pngtree.com/png-clipart/20190619/original/pngtree-vector-picture-icon-png-image_4013511.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Sotssass</div>
                            </div>
                            </a>
                        </div>
                        <div class="designer_image">
                            <a href="designer_versace">
                            <img class="designer__img" src="https://mostra1972.unipr.it/files/large/2d691a05c259391b312e7ce6d27f956791212426.jpg">
                            <div class="designer__text">
                                <div class="designer__title">Versace</div>
                            </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php elseif (preg_match("/\/s\/1972_mostra\/page\/designer_.*/", $path)): #the designer page has another layout but I don't like this solution ?> 
            <div id="content_home" role="main">
                <div class="head-mono">                    
                    <div class="mono_link"></div>
                    <div class="arrows_top">
                        <span class="arrow-top-left"><img src="/themes/1972_thedaily/asset/img/chevron-left-solid.png"></span>
                        <span class="arrow-top-right"><img src="/themes/1972_thedaily/asset/img/chevron-right-solid.png"></span>
                    </div>
                </div>
                <div class="social-button-designer">
                    <button class="social facebook" data-url="<?php echo $this->serverUrl(true); ?>" title="Share on Facebook">
                        <i class="fa fa-facebook"></i>
                    </button>
                    <button class="social twitter" data-url="<?php echo $this->serverUrl(true); ?>" title="Share on Twitter">
                        <i class="fa fa-twitter"></i>
                    </button>
                </div>
                <div class="scrolling-wrapper">
                    <span class='arrow-left'><img src="/themes/1972_thedaily/asset/img/chevron-left-solid.png"></span>
                    <span class='arrow-right'><img src="/themes/1972_thedaily/asset/img/chevron-right-solid.png"></span>
                    <?php echo $this->content; ?>
                </div>
            </div>
        <?php else: ?>
            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>
        <?php endif; ?>
        <footer>
            <?php if ($footerContent = $this->themeSetting('footer')): ?>
                <?php echo $footerContent; ?>
            <?php else: ?>
                <?php echo $this->translate('Powered by Omeka S'); ?>
            <?php endif; ?>
        </footer>
    </body>
</html>